export const REMOVE_CURRENT_DRIVER = "REMOVE_CURRENT_DRIVER";
export const SET_CURRENT_DRIVER = "SET_CURRENT_DRIVER";
export const UPDATE_CURRENT_DRIVER = "UPDATE_CURRENT_DRIVER"
export const LOGOUT = "LOGOUT"
